drop table if EXISTS navigation;

create table navigation(
    id int primary key auto_increment,
    name varchar(255) not null,
    connected_name varchar(255)
);

insert into navigation (name, connected_name)
values ("Accueil", NULL),
        ("Jeux vidéo", NULL,),
        ("Livres", NULL),
        ("Films", NULL),
        ("Theories", NULL),
        ("Série principale", 'Jeux vidéo'),
        ("Five Nights at Freddy's", 'Série principale'),
        ("Five Nights at Freddy's 2", 'Série principale'),
        ("Five Nights at Freddy's 3", 'Série principale'),
        ("Five Nights at Freddy's 4", 'Série principale'),
        ("Five Nights at Freddy's: Sister Location", 'Série principale'),
        ("Freddy Fazbear's Pizzeria Simulator", 'Série principale'),
        ("Ultimate Custom Night", 'Série principale'),
        ("Five Nights at Freddy's: Help Wanted", 'Série principale'),
        ("Five Nights at Freddy's: Security Breach", 'Série principale'),
        ("Five Nights at Freddy's: Help Wanted 2", 'Série principale'),
        ("Five Nights at Freddy's: Secret of the Mimic", 'Série principale'),
        ("Spin-off", 'Jeux vidéo'),
        ("Romans", 'Livres'),
        ("Trilogie des romans", 'Romans'),
        ("Fazbear Frights", 'Romans'),
        ("Tales from the Pizzaplex", 'Romans'),
        ("The Silver Eyes", 'Trilogie des romans'),
        ("The Twisted Ones", 'Trilogie des romans'),
        ("The Fourth Closet", 'Trilogie des romans'),
        ("Fazbear Frights 1: Into The Pit", 'Fazbear Frights'),
        ("Fazbear Frights 2: Fetch", 'Fazbear Frights'),
        ("Fazbear Frights 3: 1/35 A.M", 'Fazbear Frights'),
        ("Fazbear Frights 4: Step Closer", 'Fazbear Frights'),
        ("Fazbear Frights 5: Bunny Call", 'Fazbear Frights'),
        ("Fazbear Frights 6: Blackbird", 'Fazbear Frights'),
        ("Fazbear Frights 7: The Cliffs", 'Fazbear Frights'),
        ("Fazbear Frights 8: Gumdrop Angel", 'Fazbear Frights'),
        ("Fazbear Frights 9: The Puppet Carver", 'Fazbear Frights'),
        ("Fazbear Frights 10: Friendly Face", 'Fazbear Frights'),
        ("Tales from the Pizzaplex 1: Lally's Game", 'Tales from the Pizzaplex'),
        ("Tales from the Pizzaplex 2: HAPPS", 'Tales from the Pizzaplex'),
        ("Tales from the Pizzaplex 3: Somniphobia", 'Tales from the Pizzaplex'),
        ("Tales from the Pizzaplex 4: Submechanophobia", 'Tales from the Pizzaplex'),
        ("Tales from the Pizzaplex 5: The Bobbiedots Conclusion", 'Tales from the Pizzaplex'),
        ("Tales from the Pizzaplex 6: Nexie", 'Tales from the Pizzaplex'),
        ("Tales from the Pizzaplex 7: Tiger Rock", 'Tales from the Pizzaplex'),
        ("Tales from the Pizzaplex 8: B7-2", 'Tales from the Pizzaplex');
       